### ISSUE TITLE
support for ROS2

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/osr-rover-code#109]
A meta-issue for supporting ROS2. ROS2 is slowly becoming the new default and folks will be trying to switch over over the next months/years. This is a good opportunity to become familiar with the new standard and attract more developers.

Feel free to chime in with thoughts.

**Comment by ericjunkins** [comment]
Are you thinking we should support both ROS and ROS2?

**Comment by Achllle** [comment]
I'm thinking we should have a branch for ROS2 with ROS1 our default. Any changes that apply to both can be backported. And then if ROS2 becomes mature and we fully support it, we can decide to switch over. But we have to put in the effort first, which I'm happy to do

**Comment by Achllle** [comment]
Initial work on branch [Achllle/osr-rover-code/iss109_ros2fox](https://github.com/Achllle/osr-rover-code/tree/iss109_ros2foxy)

**Comment by Achllle** [comment]
Closing since there is now proper ROS2 support - decision on making that the main branch will follow later
