### ISSUE TITLE
Rover bringup instructions don't work for Ubuntu

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/osr-rover-code#116]
In the [rover_bringup.md](https://github.com/nasa-jpl/osr-rover-code/blob/master/setup/rover_bringup.md), in Section 2: Automatic bringup with init script, the first instruction  is 
```
cd /home/pi/osr/Init\ Scripts
```

However, in the Ubuntu install (instead of Raspbian) this directory does not exist.  It is instead
```
ubuntu@ubuntu:home/osr_ws
```

These directions would benefit from updating to the currently preferred Ubuntu install.

**Comment by Achllle** [comment]
Edited formatting of your question to render nicely.

Looks like this has been either fixed or is invalid. Please reopen or create a new issue if that is incorrect
