### ISSUE TITLE
Clone and build the rover code "cd.." instruction out of sequence

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/osr-rover-code#117]
[NOTE: comment lines removed to avoid bizarre formatting]
In [rpi.md](https://github.com/nasa-jpl/osr-rover-code/blob/master/setup/rpi.md), in Section 4.2 Clone and build the rover code, the install directions state:

```
sudo apt-get install git
cd ~/osr_ws/src
git clone https://github.com/nasa-jpl/osr-rover-code.git
rosdep install --from-paths src --ignore-src
cd ..
catkin_make
```

However, this leads to the error message right after the rosdep install command:

```
given path 'src' does not exist
```

because it is already in the src directory.
the command
`cd ..`
should come first (to move up one level) making the instructions:

```
sudo apt-get install git
cd ~/osr_ws/src
git clone https://github.com/nasa-jpl/osr-rover-code.git
cd ..
rosdep install --from-paths src --ignore-src
catkin_make
```

**Comment by Achllle** [comment]
Updated formatting. For multi-line code, use triple backticks ``` instead of the quote (>) formatting. You can edit your post to see how that works.

This is also a great one to try fixing yourself. I'll open a Pull Request to show how easy it is.
