### ISSUE TITLE
Seeing ZeroDivisionError when odometry is enabled

### ISSUE THREAD

**Issue by veeresht** [nasa-jpl/osr-rover-code#134]
![image](https://user-images.githubusercontent.com/760356/116801733-46e8bd00-aac1-11eb-93ba-a2fe4561fec3.png)

Seeing this ZeroDivisionError when the rover is brought up with `enable_odometry:=true` option, which indicates that `self.curr_turning_radius` is 0 or close to 0.

**Comment by Achllle** [comment]
Thanks for the find. I am unable to reproduce this but I can see the edge case where this would happen. I will submit a simple patch with a try-except wrapper as a fix ASAP.

**Comment by Achllle** [comment]
This happens when the angle of the wheels is +/- 55.4 degrees which is an invalid value since the max angle is around 45 degrees. You should check your wheel calibration if you're building an unmodified rover.

**Comment by apollokit** [comment]
i forget, @Achllle you closed this out with a pr right?

**Comment by Achllle** [comment]
Correct
