### ISSUE TITLE
change osr_launch.py to osr_mod_launch.py

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/osr-rover-code#148]
In foxy-devel:
[https://github.com/nasa-jpl/osr-rover-code/blob/foxy-devel/setup/rpi.md](url)
In section 4.2 Clone and build the rover code the instructions:

> The rover has some customizable settings that will overwrite the default values. Whether you have any changes compared to the defaults or not, you have to manually create these files:
```
cd ~/osr_ws/src/osr-rover-code/ROS/osr_bringup/config
touch osr_params_mod.yaml roboclaw_params_mod.yaml
```
should also include
```
cd ~/osr_ws/src/osr-rover-code/ROS/osr_bringup/launch
touch osr_mod_launch.py
```
> You might also want to modify the file osr-rover-code/ROS/osr_bringup/launch/**osr_launch.py** to change the velocities the gamepad controller will send to the rover. 

Should say

> You might also want to modify the file osr-rover-code/ROS/osr_bringup/launch/**osr_mod_launch.py** to change the velocities the gamepad controller will send to the rover.

**Comment by Achllle** [comment]
no longer relevant
