### ISSUE TITLE
Permission denied to create symbolic links

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/osr-rover-code#149]
In branch **foxy-devel**
[https://github.com/nasa-jpl/osr-rover-code/blob/foxy-devel/setup/rover_bringup.md](url)
In section **3 Automatic bringup with launch script**
This command gets permission error:
`ubuntu@AUDACITY:~/osr_ws/src/osr-rover-code/init_scripts$ ln -s $(pwd)/launch_osr.sh /usr/local/bin/launch_osr.sh`
`ln: failed to create symbolic link '/usr/local/bin/launch_osr.sh': Permission denied`
possibly because /usr/local/bin is owned by root.
Using sudo... allows it.
Same with:
`ln -s $(pwd)/osr_paths.sh /usr/local/bin/osr_paths.sh
`

Also - in the osr_startup.service command table, the underscore between osr and startup doesn't display.

**Comment by Achllle** [comment]
This has been fixed, the command is run with sudo now.
