### ISSUE TITLE
Automatic bringup with launch script causes "A stop job..." delay on boot & shutdown

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/osr-rover-code#150]
In branch foxy-devel:
[https://github.com/nasa-jpl/osr-rover-code/blob/foxy-devel/setup/rover_bringup.md](url)
In section **3 Automatic bringup with launch script**
Enabling the osr_startup.service causes a "A stop job is running for OSR service (1min 43s countdown)" x 3.
Disabling the service removes the stop job.
I _suspect_ it has something to do with the sudo permission in the previous issue in that the system is waiting for permission to start.
The service doesn't seem to start until the user has logged in at the desktop, not via PuTTY, as the Xbox controller will not pair until then.  
In the original ROS(1) version of OSR code, the osr_startup.service launched on bootup without stop job nor requiring log-in.

**Comment by Achllle** [comment]
I believe this is no longer an issue, but if that's incorrect, please reopen!
