### ISSUE TITLE
Update instructions in section 4.2 for ROS2 Foxy Installation

### ISSUE THREAD

**Issue by safariace** [nasa-jpl/osr-rover-code#151]
For a clean ROS2 build out, I needed to do the following to get section 4.2 to work:

rosdep install --from-paths src --ignore-src --rosdistro=foxy

Was getting an error that ROSDISTRO not set without it.  Finished with #All required rosdeps installed successfully.

For serial, needed to create the dialout group and add my username to it, for roboclawtest.py to run

**Comment by Achllle** [comment]
Didn't get response on #153 so closing this
