### ISSUE TITLE
5.2 Copy udev rules - incorrect path

### ISSUE THREAD

**Issue by JHPHELAN** [nasa-jpl/osr-rover-code#155]
Following [https://github.com/nasa-jpl/osr-rover-code/blob/foxy-devel/setup/rpi.md](url) in section 5.2 Copy udev rules
the instruction
`cd ~/osr_ws/src/osr-rover-code/config`
is incorrect.  It should be
`cd ~/osr_ws/osr-rover-code/ROS/osr_bringup/config`

**Comment by ericjunkins** [comment]
Thanks for bringing this to our attention. Because it seems there is already a solution to this we would greatly appreciate you making a PR with this. It helps us, it helps you, it helps everyone!

**Comment by Achllle** [comment]
The original instruction is correct. Please check again.
