### ISSUE TITLE
[bug report] screen.py status check functions: scaling incorrect

### ISSUE THREAD

**Issue by SallyTYT** [nasa-jpl/osr-rover-code#160]
https://github.com/nasa-jpl/osr-rover-code/blob/master/ROS/led_screen/src/screen.py

The status data should not be scaled by a factor of 0.1

line 70 >> battery *= 0.1 
line 96 >> val = temperature[i][j] * 0.1
line 119 >> val = currents[i][j] * 0.1
line 140 >> val = currents[i][j] * 0.1

**Comment by ericjunkins** [comment]
Can you give more context on why you think this is incorrect? I believe it is correct as is currently

**Comment by SallyTYT** [comment]
@ericjunkins

If scaling by 0.1, the `out_msg[3], [5]~[12]` would always be zero,
![image](https://user-images.githubusercontent.com/64485819/193174083-f2447400-20ac-4608-b5fb-5913daea8d6d.png)
And the LED screen would always be like this,
![d92461e39f12c3b28d64d9b661b8cbb](https://user-images.githubusercontent.com/64485819/193175842-f9ebad79-c0f1-4b57-a96a-f81d79d5b728.jpg)


If removing the scaling, the `out_msg` would have valid values, It works just like this document describes https://github.com/nasa-jpl/osr-rover-code/blob/master/OsrScreen/README.md
![image](https://user-images.githubusercontent.com/64485819/193174897-3f9cb1ef-80fa-40fb-88cf-fd68ff399ecd.png)
And the LED screen would work well too,
![f64c068e0fa90d13c1da91fa10e54ef](https://user-images.githubusercontent.com/64485819/193175821-012bd4d5-92a8-480b-9e5e-772788440cc1.jpg)
