### ISSUE TITLE
roslaunch node boot sequence

### ISSUE THREAD

**Issue by ericjunkins** [nasa-jpl/osr-rover-code#33]
The rosnodes need a boot sequence forced to make sure that the motor_controller node completes its' initialization before other nodes start

**Comment by Achllle** [comment]
ROS is distributed and thus you cannot enforce which nodes run when. The way to deal with this is to wait for certain services or topics or so to come up before you continue.

**Comment by ericjunkins** [comment]
It's not strictly enforced no, this was to make sure that the motor_controller was fully initialized before any parameters were passed to the other nodes, which can be monitored by flags in the system. What it should do is the motor controller node, and wait until all it is pulled/pushed all the necessary operating parameters to it, and then give the go-ahead flag to the rest of the nodes the begin their initialization.

**Comment by Achllle** [comment]
No longer relevant
