### ISSUE TITLE
Startup service files inconsistencies and errors

### ISSUE THREAD

**Issue by Roger-random** [nasa-jpl/osr-rover-code#37]
## User name

```LaunchOSR.sh``` is based on username ```pi```
```osr_startup.service``` is based on username ```ubuntu```

They should be consistent.

Plus the Software Controls PDF should mention an user may need to edit the username in these files to match what they have configured.

## Syntax errors in ```osr_startup.service```

```WorkingDirectory=/home/ubuntu/LaunchOSR.sh```
This points to the shell script, should point to a directory instead.

```ExecStart=/home/ubuntu/```
This is pointing to a directory, should point to the script instead.

```Wantedby=multi-user.target```
This parameter is case sensitive and should be ```WantedBy```

**Comment by Achllle** [comment]
This has been solved in a recent PR
