### ISSUE TITLE
osr_msgs: list --> fields

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/osr-rover-code#55]
Currently the messages contain an ordered list for each motor which is hard to interpret and error prone. Either the messages should be converted to contain specific fields, e.g.:

```
drive:
  int32 left_front
  int32 left_middle
  int32 left_back
  int32 right_front
  int32 right_middle
  int32 right_back
steer:
  int32 left_front
  int32 left_back
  int32 right_front
  int32 right_back
```

OR the order should be better documented. I believe currently the order is 131M1, 131M2, 132M1, 132M2. Perhaps we want to change this to be clockwise starting front right or similar.

**Comment by Achllle** [comment]
We can also use the commonly used `sensor_msgs/JointState` message which includes naming, position, velocity, effort. And works with JointStatePublisher as well as [RobotStatePublisher](http://wiki.ros.org/robot_state_publisher) nodes which we'll need to do anyways if we want to set up ROS tf2 and RViz and the like easily

**Comment by Achllle** [comment]
Similarly, the rosparams should also not be lists which are ambiguous.

**Comment by ericjunkins** [comment]
I agree, each of these should have individual field names, instead of lists. It was convenient to do things as lists initially, however is confusing and ambiguous as to what is being accomplished at each step.
