### ISSUE TITLE
Add required=true arg to crucial launch files

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/osr-rover-code#56]
Currently crucial nodes are respawned when they crash. Instead, they should be set to required=True (perhaps if they repeatedly fail) so that everything stops when this happens. No use in trying to run when a crucial node doesn't work.

**Comment by ericjunkins** [comment]
Good change proposal. I think let's shelve this until the end of all the other changes, but I agree to move to this.

**Comment by ericjunkins** [comment]
@gfosmire
