### ISSUE TITLE
Consider switching to SI units

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/osr-rover-code#59]
To be consistent with the robotics and ROS community, it would make sense to switch to SI units for all calculations. See ROS' [REP103](https://www.ros.org/reps/rep-0103.html). Instead of degrees and degrees per second, we would use radian and rad/s as well as meter and m/s iso inches.

Happy to do this if there is consensus on this.

**Comment by ericjunkins** [comment]
This makes sense to do yes. Initially units of inches were chosen as parts are all english-unit parts, and thus was easier-ish in that regard. But when the transition to ROS happened SI unit conversion should have happened as well.

**Comment by Achllle** [comment]
Opening a PR for this once #48 and some other are in.
