### ISSUE TITLE
Clean up .pyc files

### ISSUE THREAD

**Issue by pabloriveracelerity** [nasa-jpl/osr-rover-code#6]
FIles should be cleaned up and a .gitignore added to avoid committing them again

**Comment by vssystemluba** [comment]
This was solved with c9759b99b242a45ae557495086270c87808ff805.

**Comment by pabloriveracelerity** [comment]
Yes, I saw that after creating the issue (sorry!). Went ahead and sent a PR with a .gitignore that covers more use cases. :)
