### ISSUE TITLE
calculateTargetDeg method clipping code runs but not used

### ISSUE THREAD

**Issue by Achllle** [nasa-jpl/osr-rover-code#60]
The code for `calculateTargetDeg` contains something like:

```
ang1 = int(math.degrees(math.atan(self.d1 / (abs(r) + self.d3))))
ang2 = int(math.degrees(math.atan(self.d2 / (abs(r) + self.d3))))
ang3 = int(math.degrees(math.atan(self.d2 / (abs(r) - self.d3))))
ang4 = int(math.degrees(math.atan(self.d1 / (abs(r) - self.d3))))

angles = [ang1, ang2, ang3, ang4]
for i in range(4):
	if angles[i] < -45:
		angles[i] = -43
	elif angles[i] > 45:
		angles[i] = 43

if radius > 0:
	return [ang2, -ang1, -ang4, ang3]
else:
	return [-ang4, ang3, ang2, -ang1]
```

The middle section seems to be clipping values outside the range abs(45) to abs(43) but those values are assigned to the variables `angles`, which isn't used in the following return value calculation.

Options:

1. remove clipping, it's not functional code
2. fix the clipping if it needs to stay

**Comment by ericjunkins** [comment]
good find, i think it is better to have the clipped values, because of any mechanical slippage the calibration can drift over time slightly and might get to a point where you can either damage the motor or the hard-stop 3D printed piece if it drifts enough.
