### ISSUE TITLE
Add package dependency list for ease of getting started

### ISSUE THREAD

**Issue by asasine** [nasa-jpl/osr-rover-code#8]
The source has some pip dependencies which aren't explicitly documented.

Using a _requirements.txt_ or a workflow like [Pipenv](https://pypi.org/project/pipenv/) would aid developers with getting started. Note that Pipenv is the [recommended tool](https://packaging.python.org/guides/tool-recommendations/#application-dependency-management) by the Python for dependency management.

**Comment by asasine** [comment]
Because the dependencies for this project are not limited to pip (see section 1.2.1 of [Software Steps](https://github.com/nasa-jpl/open-source-rover/blob/master/Software/Software%20Steps.pdf) in main repository), this likely cannot be solved using only pip or its flavors.

**Comment by pabloriveracelerity** [comment]
A requirements file could be added with a note on the README that mentions the additional packages. It's still a good idea to have one.

**Comment by pabloriveracelerity** [comment]
We could probably close this one for the time being and then open a new issue for pipenv integration. Given that using pipenv would require adjusting the documentation. Thoughts?

**Comment by Achllle** [comment]
I would agree on closing. Since this is a ROS project, pip requirements do not make sense and instead dependencies should go in `package.xml`. The recommended install tool before actual bloom release would be rosdep.

**Comment by Achllle** [comment]
@ericjunkins this can be closed. We will track dependencies in package.xml which currently only is pyserial, which was added in #43
