### ISSUE TITLE
Incorrect "r" calculation in calculating drive velocities

### ISSUE THREAD

**Issue by ericjunkins** [nasa-jpl/osr-rover-code#94]
@Achllle, I believe that in the calculate drive velocities function in rover.py the "r" value used in v=r * omega is incorrect for the corners, lines 106, 107

` vel_corner_closest =  (radius - self.d1) * angular_velocity_center`
`vel_corner_farthest = (radius + self.d1) * angular_velocity_center`

These should be the quadrature sum including the "self.d3" as well:

sqrt ((radius - d1) ^2 + (d3)^2 )
sqrt ((radius + d1) ^2 + (d3)^2 )

**Comment by Achllle** [comment]
You are absolutely correct. I will fix this asap
